services:
  app:
    build: .
    container_name: midtrans-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/app/config.yml
    env_file:
      - .env.production
    environment:
      - ENV=production